### ISSUE TITLE
Workspace fetch is only limited to 20 per page

### ISSUE THREAD

**Issue by Bhartu1** [ausmartway/tfcvar-sec#5]
Hi,

I'm trying to run this against all the workspaces in our organization, which has around 1000+ WS. But the issue with the current code is fetching only first 20 workspaces as the api will only give 20 workspaces per page. As this is resulting the scan on only 20.
Kindly modify this by fetching all the Workspaces under org.
Have done similar thing earlier in bash-
 
#Get the list of workspaces
PAGE_COUNT=$(curl   --header "Authorization: Bearer ${TOKEN}"   --header "Content-Type: application/vnd.api+json"   https://${TF_ADDR}/api/v2/organizations/${WS_ORG}/workspaces | jq -r '.meta.pagination."total-pages"')
echo "Number of pages: ${PAGE_COUNT}"

echo -e "FETCHING LIST OF WORKSPACES"
for ((i=1;i<=${PAGE_COUNT};i++))
do
    echo -e "\nChecking for page ${i}"
    curl   --header "Authorization: Bearer ${TOKEN}"   --header "Content-Type: application/vnd.api+json"   https://${TF_ADDR}/api/v2/organizations/${WS_ORG}/workspaces?page%5Bnumber%5D=${i} | jq -r '.data[].attributes.name'  >> ws_list.json
done

**Comment by ausmartway** [comment]
Thanks @Bhartu1 , I have done a new release. please let me know if it fixes this issue.

**Comment by ausmartway** [comment]
@Bhartu1 , have you got a chance to test the new release?

**Comment by Bhartu1** [comment]
Hey Yulie,

Thanks for the response.

Still facing the same issue. It is only fetching 20 workspaces.
[cid:9f4860c9-f63e-401b-804a-8822d8a2d92b]
I've made sure that the token i use is an organization token.

Regards,
Bharathi

________________________________

**Comment by ausmartway** [comment]
Can you please print the version number?

I have tested this in an org with more than 20 workspaces and it works, please make sure you have upgraded to 0.3.4

**Comment by Bhartu1** [comment]
Hey Yulei,

Thanks for the swift resolution.

It's working now.

Thanks,
Bharathi
________________________________

**Comment by ausmartway** [comment]
Thanks @Bhartu1
